[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
signal-hook = "0.3.14"
tokio = { version = "1.19.2", features = ["full"] }
