[package]
name = "csv-convertor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
csv = "1.1.6"
csv-lib = { path = "../csv-lib" }
serde = "1.0.135"
structopt = "0.3.26"
