[package]
name = "demo1-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
tokio = { version = "1.17.0", features = ["full"] }

demo1 = { path = "../demo1/"}