[package]
name = "thebook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
timer = "0.2.0"
tokio = { version = "0.2", features = ["full"] }
tokio-cron-scheduler = "0.4.0"
