[package]
name = "tmp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
async-trait = "0.1.52"
chrono = "0.4.19"
timer = "0.2.0"
tokio = { version = "1.15.0", features = ["full"] }
